MAX_ITERATIONS = 500
TABU_TENURE = 20
NEIGHBORHOOD_SIZE = 50
MAX_SHIFT = 15
PATIENCE = 200

DIVERSIFICATION_TRIGGER = 80
DIVERSITY_WEIGHT = 5.0
DIVERSIFICATION_DURATION = 20

ELITE_SIZE = 5
INTENSIFICATION_TRIGGER = 100

MAX_UNSELECTED_FOR_INSERT = 500
